baseline_no_draft:
  active: 0
  oracle_model: meta-llama/Llama-3.2-3B
baseline_single_draft:
  active: 0
  draft1_model:
  - minghaoyan/Wide-Sheared-LLaMA-796M
  - minghaoyan/Wide-Sheared-LLaMA-543M
  - minghaoyan/Wide-Sheared-LLaMA-290M
  oracle_model:
  - meta-llama/Llama-2-70b-hf
demo_target: 0
double_draft:
  active: 1
  draft1_model:
  - minghaoyan/Wide-Sheared-LLaMA-290M
  - minghaoyan/Wide-Sheared-LLaMA-543M
  draft2_model:
  - minghaoyan/Wide-Sheared-LLaMA-543M
  - minghaoyan/Wide-Sheared-LLaMA-290M
  drafter_switch_threshold:
  - 25
  - 50
  - 75
  oracle_model:
  - meta-llama/Llama-3.2-3B
full_prompt_input_file: prompts/hellaswag.json
num_input_prompts: 10
num_spec_tokens:
- 3
stride_enable: 0
strided_prompt_output_file: prompts/hellaswag_shortened.json
test_name: real_sdraft_543_290
