#test_name: no_drafter_test_3
test_name: no_draft_and_single_draft_test_5

# Input prompts
# Don't point to an adjusted prompt file. We adjust inside the benchmark script based on size param below!
full_prompt_input_file: "prompts/hellaswag.json"
strided_prompt_output_file: "prompts/hellaswag_shortened.json"
num_input_prompts: 5

# Type of experiment
# Left most are booleans indicating if that experiment is run
#   Next indent is the list of drafter models to use 
#   Pairs listed for double draft (larger draft model, smaller draft model)
baseline_no_draft: 
  active: 1
  oracle_model: 'meta-llama/Llama-3.2-3B'

baseline_single_draft: 
  active: 1
  oracle_model: 'meta-llama/Llama-3.2-3B'
  draft1_model: 'minghaoyan/Wide-Sheared-LLaMA-796M'

double_draft: 1
# TODO: Connect this to file
num_spec_tokens: 7
